"""add arbitrage tables and fields

Revision ID: cb0d591e3f65
Revises: d72704afbbd1
Create Date: 2025-09-23 16:17:47.204628

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb0d591e3f65'
down_revision: Union[str, Sequence[str], None] = 'd72704afbbd1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.create_table(
        'arb_groups',
        sa.Column('id', sa.Integer(), primary_key=True),
        sa.Column('created_at', sa.DateTime(), server_default=sa.func.now(), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('guaranteed_profit', sa.Numeric(precision=10, scale=2), nullable=True),
    )
    # Add columns to bets
    # op.add_column(
    #     'bets',
    #     sa.Column('is_arbitrage', sa.Boolean(), nullable=False, server_default=sa.text("0"))
    # )
    # op.add_column('bets', sa.Column('arb_group_id', sa.Integer(), nullable=True))
    # op.add_column('bets', sa.Column('guaranteed_profit', sa.Numeric(precision=10, scale=2), nullable=True))

    # Drop old index (optional)
    op.drop_index(op.f('ix_bets_sportsbook'), table_name='bets')

    # Add foreign key
    op.create_foreign_key(
        "fk_bets_arb_group",
        "bets", "arb_groups",
        ["arb_group_id"], ["id"],
        ondelete="SET NULL"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_bets_arb_group", "bets", type_="foreignkey")
    op.create_index(op.f('ix_bets_sportsbook'), 'bets', ['sportsbook'], unique=False)

    # op.drop_column('bets', 'guaranteed_profit')
    # op.drop_column('bets', 'arb_group_id')
    # op.drop_column('bets', 'is_arbitrage')

    op.drop_table('arb_groups')
    # ### end Alembic commands ###
